// ============================================================
// CityPulse — Pittsburgh Seed Data
// Realistic figures based on Pittsburgh public data (2023-24).
// All numbers are approximate but defensible.
// ============================================================

import {
  City, Neighborhood, Resident, AgentGroup,
  Policy, Bridge, GameEvent, SimulationSnapshot,
  Season,
} from './types';

// ------ CITY SEED -------------------------------------------

export const initialCity: City = {
  id: 'pittsburgh',
  name: 'Pittsburgh',
  turn: 1,
  year: 3,
  day: 12,
  season: 'spring' as Season,
  // Population (city proper ~300k, metro ~2.3M)
  population: 302_000,
  metroPopulation: 2_370_000,
  unemploymentRate: 0.048,
  // Finance — Pittsburgh operates ~$600M annual budget
  treasury: 2_480_000,          // city treasury surplus
  revenue: 2_910_000,           // per-turn (per quarter)
  expenses: 2_430_000,
  // Composite scores
  happiness: 72,
  approval: 68,
  transitScore: 58,
  safetyScore: 64,
  environmentScore: 55,
  // Housing
  housingSupply: 148_000,       // occupied units citywide
  averageRent: 1_340,           // $/month (below national median)
  // Pittsburgh-specific
  bridgeConditionAvg: 61,       // 446 bridges, many rated deficient
  riverFloodRisk: 0.12,
  airQualityIndex: 74,          // moderate — Mon Valley steel legacy
  taxExemptPropertyShare: 0.42, // ~42% of assessed value tax-exempt (universities, hospitals, nonprofits)
};

// ------ NEIGHBORHOODS ---------------------------------------

export const initialNeighborhoods: Neighborhood[] = [
  // === THREE CORE PLAYABLE (income tiers) ===
  {
    id: 'shadyside',
    name: 'Shadyside',
    mapX: 0.72, mapY: 0.28,
    population: 13_200,
    incomeGroup: 'higher',
    medianIncome: 94_000,
    renterFraction: 0.61,
    averageRent: 1_980,
    propertyValue: 385_000,
    housingUnits: 7_100,
    vacancyRate: 0.05,
    jobs: 4_200,
    happiness: 81,
    transitAccess: 62,
    safetyScore: 78,
    hillsideRisk: 0.05,
    transitDependence: 0.22,
    bridgeCondition: 80,
    taxExemptPropertyShare: 0.18,
    gentrificationPressure: 0.3,
    description: 'Upscale East End neighborhood with tree-lined streets and Walnut Street retail.',
    historicalNote: 'Home to Shadyside Hospital and some of Pittsburgh\'s highest property values.',
  },
  {
    id: 'lawrenceville',
    name: 'Lawrenceville',
    mapX: 0.62, mapY: 0.22,
    population: 8_400,
    incomeGroup: 'middle',
    medianIncome: 52_000,
    renterFraction: 0.72,
    averageRent: 1_540,
    propertyValue: 248_000,
    housingUnits: 4_800,
    vacancyRate: 0.07,
    jobs: 3_100,
    happiness: 68,
    transitAccess: 70,
    safetyScore: 65,
    hillsideRisk: 0.10,
    transitDependence: 0.38,
    bridgeCondition: 72,
    taxExemptPropertyShare: 0.12,
    gentrificationPressure: 0.75,   // rapidly gentrifying
    description: 'Former industrial riverfront district along Butler Street, rapidly gentrifying.',
    historicalNote: 'Once home to Arsenal of the Union; now Pittsburgh\'s arts and restaurant hub.',
  },
  {
    id: 'homewood',
    name: 'Homewood',
    mapX: 0.82, mapY: 0.35,
    population: 6_800,
    incomeGroup: 'lower',
    medianIncome: 28_500,
    renterFraction: 0.55,
    averageRent: 740,
    propertyValue: 68_000,
    housingUnits: 4_200,
    vacancyRate: 0.28,           // high vacancy, land-bank lots
    jobs: 900,
    happiness: 42,
    transitAccess: 72,
    safetyScore: 42,
    hillsideRisk: 0.08,
    transitDependence: 0.64,
    bridgeCondition: 58,
    taxExemptPropertyShare: 0.08,
    gentrificationPressure: 0.12,
    description: 'Historic East End neighborhood with strong community institutions and high transit dependence.',
    historicalNote: 'One of Pittsburgh\'s oldest Black neighborhoods, experiencing decades of disinvestment.',
  },
  // === ADDITIONAL NEIGHBORHOODS ===
  {
    id: 'oakland',
    name: 'Oakland',
    mapX: 0.65, mapY: 0.38,
    population: 25_000,
    incomeGroup: 'middle',
    medianIncome: 38_000,        // college student effect
    renterFraction: 0.88,
    averageRent: 1_620,
    propertyValue: 312_000,
    housingUnits: 14_000,
    vacancyRate: 0.04,
    jobs: 42_000,               // hospitals, universities
    happiness: 62,
    transitAccess: 85,
    safetyScore: 60,
    hillsideRisk: 0.12,
    transitDependence: 0.55,
    bridgeCondition: 74,
    taxExemptPropertyShare: 0.68, // Pitt, CMU, UPMC largely tax-exempt
    gentrificationPressure: 0.45,
    description: 'Pittsburgh\'s eds-and-meds hub: University of Pittsburgh, CMU, and UPMC all headquartered here.',
    historicalNote: 'The Cathedral of Learning (42-story gothic tower) defines the skyline.',
  },
  {
    id: 'golden_triangle',
    name: 'Golden Triangle',
    mapX: 0.38, mapY: 0.48,
    population: 3_500,
    incomeGroup: 'higher',
    medianIncome: 82_000,
    renterFraction: 0.95,
    averageRent: 2_100,
    propertyValue: 520_000,
    housingUnits: 2_200,
    vacancyRate: 0.08,
    jobs: 78_000,               // CBD employment
    happiness: 70,
    transitAccess: 95,
    safetyScore: 68,
    hillsideRisk: 0.02,
    transitDependence: 0.62,
    bridgeCondition: 76,
    taxExemptPropertyShare: 0.22,
    gentrificationPressure: 0.35,
    description: 'Downtown Pittsburgh in the wedge between the Allegheny and Monongahela rivers.',
    historicalNote: 'The Point — where the rivers meet — is home to Point State Park and its iconic fountain.',
  },
  {
    id: 'mount_washington',
    name: 'Mount Washington',
    mapX: 0.42, mapY: 0.65,
    population: 7_900,
    incomeGroup: 'middle',
    medianIncome: 48_000,
    renterFraction: 0.48,
    averageRent: 1_180,
    propertyValue: 195_000,
    housingUnits: 4_500,
    vacancyRate: 0.06,
    jobs: 1_200,
    happiness: 65,
    transitAccess: 55,
    safetyScore: 70,
    hillsideRisk: 0.35,          // steep bluffs
    transitDependence: 0.44,
    bridgeCondition: 65,
    taxExemptPropertyShare: 0.10,
    gentrificationPressure: 0.28,
    description: 'Hilltop neighborhood overlooking downtown from the south bank of the Mon.',
    historicalNote: 'Two Duquesne Inclines (funicular railways) connect residents to downtown.',
  },
  {
    id: 'hill_district',
    name: 'Hill District',
    mapX: 0.50, mapY: 0.38,
    population: 12_000,
    incomeGroup: 'lower',
    medianIncome: 22_000,
    renterFraction: 0.62,
    averageRent: 680,
    propertyValue: 55_000,
    housingUnits: 7_800,
    vacancyRate: 0.32,
    jobs: 1_400,
    happiness: 38,
    transitAccess: 68,
    safetyScore: 38,
    hillsideRisk: 0.20,
    transitDependence: 0.70,
    bridgeCondition: 52,
    taxExemptPropertyShare: 0.12,
    gentrificationPressure: 0.20,
    description: 'Historic African American cultural district adjacent to downtown.',
    historicalNote: 'August Wilson\'s birthplace; the Hill was bisected by the Civic Arena\'s construction.',
  },
  {
    id: 'strip_district',
    name: 'Strip District',
    mapX: 0.52, mapY: 0.25,
    population: 2_800,
    incomeGroup: 'middle',
    medianIncome: 61_000,
    renterFraction: 0.85,
    averageRent: 1_780,
    propertyValue: 295_000,
    housingUnits: 1_800,
    vacancyRate: 0.06,
    jobs: 5_200,
    happiness: 72,
    transitAccess: 78,
    safetyScore: 65,
    hillsideRisk: 0.05,
    transitDependence: 0.35,
    bridgeCondition: 70,
    taxExemptPropertyShare: 0.14,
    gentrificationPressure: 0.55,
    description: 'Riverfront warehouse district turned tech and food market corridor.',
    historicalNote: 'Saturday morning produce market has operated since 1900.',
  },
  {
    id: 'south_side_flats',
    name: 'South Side Flats',
    mapX: 0.48, mapY: 0.58,
    population: 11_000,
    incomeGroup: 'middle',
    medianIncome: 44_000,
    renterFraction: 0.74,
    averageRent: 1_250,
    propertyValue: 172_000,
    housingUnits: 6_200,
    vacancyRate: 0.08,
    jobs: 3_800,
    happiness: 62,
    transitAccess: 64,
    safetyScore: 58,
    hillsideRisk: 0.08,
    transitDependence: 0.42,
    bridgeCondition: 68,
    taxExemptPropertyShare: 0.10,
    gentrificationPressure: 0.40,
    description: 'Bar and restaurant strip along Carson Street, rapidly modernizing.',
    historicalNote: 'Former steel mill site; J&L Steel occupied this riverbank for a century.',
  },
  {
    id: 'hazelwood',
    name: 'Hazelwood',
    mapX: 0.72, mapY: 0.55,
    population: 4_900,
    incomeGroup: 'lower',
    medianIncome: 26_000,
    renterFraction: 0.52,
    averageRent: 750,
    propertyValue: 58_000,
    housingUnits: 3_400,
    vacancyRate: 0.22,
    jobs: 700,
    happiness: 44,
    transitAccess: 56,
    safetyScore: 48,
    hillsideRisk: 0.25,
    transitDependence: 0.60,
    bridgeCondition: 55,
    taxExemptPropertyShare: 0.08,
    gentrificationPressure: 0.15,
    description: 'Post-industrial neighborhood on the Monongahela with significant reinvestment potential.',
    historicalNote: 'Former home of the Hazelwood coke works; now hosts Hazelwood Green tech campus.',
  },
];

// ------ RESIDENTS -------------------------------------------

export const initialResidents: Resident[] = [
  {
    id: 'res-001',
    name: 'Diane Kowalski',
    age: 52,
    occupation: 'Registered Nurse (UPMC Presbyterian)',
    neighborhood: 'lawrenceville',
    incomeGroup: 'middle',
    annualIncome: 74_000,
    isHomeowner: false,
    housingCost: 1_540,
    commuteMins: 24,
    commuteMode: 'bus',
    familySize: 2,
    taxSensitivity: 0.45,
    housingSensitivity: 0.72,
    transitSensitivity: 0.80,
    environmentSensitivity: 0.55,
    governmentTrust: 0.52,
    happiness: 66,
    mood: 'content',
    policySupport: {},
    archetype: 'healthcare_worker',
    portraitColor: '#6366F1',
    portraitInitials: 'DK',
    memories: [],
    currentQuote: 'My rent went up $200 this year. I love this neighborhood but I\'m not sure how long I can stay.',
  },
  {
    id: 'res-002',
    name: 'Marcus Williams',
    age: 61,
    occupation: 'Retired Steelworker (USS Mon Valley)',
    neighborhood: 'homewood',
    incomeGroup: 'lower',
    annualIncome: 24_000,
    isHomeowner: true,
    housingCost: 480,
    commuteMins: 0,
    commuteMode: 'walk',
    familySize: 1,
    taxSensitivity: 0.85,
    housingSensitivity: 0.55,
    transitSensitivity: 0.65,
    environmentSensitivity: 0.40,
    governmentTrust: 0.28,
    happiness: 38,
    mood: 'frustrated',
    policySupport: {},
    archetype: 'retired_mill_worker',
    portraitColor: '#DC2626',
    portraitInitials: 'MW',
    memories: [],
    currentQuote: 'They closed the mill, then the store, then the school. Now they want to gentrify us out too.',
  },
  {
    id: 'res-003',
    name: 'Priya Sharma',
    age: 34,
    occupation: 'Robotics Engineer (CMU spinoff)',
    neighborhood: 'shadyside',
    incomeGroup: 'higher',
    annualIncome: 138_000,
    isHomeowner: false,
    housingCost: 2_100,
    commuteMins: 18,
    commuteMode: 'bike',
    familySize: 1,
    taxSensitivity: 0.30,
    housingSensitivity: 0.40,
    transitSensitivity: 0.55,
    environmentSensitivity: 0.80,
    governmentTrust: 0.65,
    happiness: 82,
    mood: 'hopeful',
    policySupport: {},
    archetype: 'tech_professional',
    portraitColor: '#8B5CF6',
    portraitInitials: 'PS',
    memories: [],
    currentQuote: 'Pittsburgh genuinely surprised me. The tech scene is real and the cost of living is amazing compared to the Bay.',
  },
  {
    id: 'res-004',
    name: 'Ray Costello',
    age: 45,
    occupation: 'Union Steamfitter (UA Local 449)',
    neighborhood: 'south_side_flats',
    incomeGroup: 'middle',
    annualIncome: 88_000,
    isHomeowner: true,
    housingCost: 1_100,
    commuteMins: 32,
    commuteMode: 'car',
    familySize: 4,
    taxSensitivity: 0.65,
    housingSensitivity: 0.50,
    transitSensitivity: 0.30,
    environmentSensitivity: 0.35,
    governmentTrust: 0.45,
    happiness: 64,
    mood: 'neutral',
    policySupport: {},
    archetype: 'union_tradesperson',
    portraitColor: '#059669',
    portraitInitials: 'RC',
    memories: [],
    currentQuote: 'There\'s still good union work here if you know where to look. But the young guys aren\'t joining like they used to.',
  },
  {
    id: 'res-005',
    name: 'Latoya Brown',
    age: 39,
    occupation: 'Port Authority Bus Operator',
    neighborhood: 'homewood',
    incomeGroup: 'lower',
    annualIncome: 54_000,
    isHomeowner: true,
    housingCost: 720,
    commuteMins: 48,
    commuteMode: 'bus',
    familySize: 3,
    taxSensitivity: 0.55,
    housingSensitivity: 0.60,
    transitSensitivity: 0.90,
    environmentSensitivity: 0.50,
    governmentTrust: 0.55,
    happiness: 48,
    mood: 'frustrated',
    policySupport: {},
    archetype: 'transit_worker',
    portraitColor: '#EF4444',
    portraitInitials: 'LB',
    memories: [],
    currentQuote: 'I drive the 71C every day through neighborhoods that haven\'t seen a new bus shelter in fifteen years.',
  },
  {
    id: 'res-006',
    name: 'Dr. James Park',
    age: 48,
    occupation: 'University Adjunct (Pitt History Dept.)',
    neighborhood: 'oakland',
    incomeGroup: 'lower',
    annualIncome: 36_000,
    isHomeowner: false,
    housingCost: 1_200,
    commuteMins: 12,
    commuteMode: 'walk',
    familySize: 1,
    taxSensitivity: 0.60,
    housingSensitivity: 0.85,
    transitSensitivity: 0.70,
    environmentSensitivity: 0.65,
    governmentTrust: 0.42,
    happiness: 45,
    mood: 'frustrated',
    policySupport: {},
    archetype: 'precarious_academic',
    portraitColor: '#F59E0B',
    portraitInitials: 'JP',
    memories: [],
    currentQuote: 'I have a PhD and I qualify for food assistance. Something is fundamentally broken.',
  },
  {
    id: 'res-007',
    name: 'Sofia Marchetti',
    age: 42,
    occupation: 'Restaurant Owner (Butler Street, Lawrenceville)',
    neighborhood: 'lawrenceville',
    incomeGroup: 'middle',
    annualIncome: 68_000,
    isHomeowner: false,
    housingCost: 1_650,
    commuteMins: 5,
    commuteMode: 'walk',
    familySize: 2,
    taxSensitivity: 0.75,
    housingSensitivity: 0.78,
    transitSensitivity: 0.40,
    environmentSensitivity: 0.45,
    governmentTrust: 0.50,
    happiness: 60,
    mood: 'neutral',
    policySupport: {},
    archetype: 'small_business_owner',
    portraitColor: '#D97706',
    portraitInitials: 'SM',
    memories: [],
    currentQuote: 'My landlord just raised the commercial rent 40%. He says the neighborhood\'s \'up-and-coming\'. I\'m the one who made it that way.',
  },
  {
    id: 'res-008',
    name: 'Darnell Carter',
    age: 36,
    occupation: 'Public School Teacher (Pittsburgh Public)',
    neighborhood: 'hill_district',
    incomeGroup: 'lower',
    annualIncome: 48_000,
    isHomeowner: false,
    housingCost: 850,
    commuteMins: 22,
    commuteMode: 'bus',
    familySize: 2,
    taxSensitivity: 0.50,
    housingSensitivity: 0.65,
    transitSensitivity: 0.75,
    environmentSensitivity: 0.60,
    governmentTrust: 0.48,
    happiness: 52,
    mood: 'neutral',
    policySupport: {},
    archetype: 'public_school_teacher',
    portraitColor: '#2563EB',
    portraitInitials: 'DC',
    memories: [],
    currentQuote: 'My students come from three different zip codes. Some are walking, some are on the 54C. When the 54C gets cut, I lose kids.',
  },
];

// ------ AGENT GROUPS (sentiment panel) ----------------------

export const initialAgentGroups: AgentGroup[] = [
  {
    id: 'group-lower',
    label: 'Lower Income',
    incomeGroup: 'lower',
    populationRepresented: 89_000,
    medianIncome: 26_000,
    renterFraction: 0.58,
    currentSentiment: 42,
    policyPreferences: {
      housing: 0.92, transit: 0.88, taxes: 0.25,
      safety: 0.78, business: 0.55, environment: 0.60,
    },
    currentQuote: '"Need more affordable housing. Rents are squeezing us out."',
    avatarColor: '#EF4444',
  },
  {
    id: 'group-middle',
    label: 'Middle Income',
    incomeGroup: 'middle',
    populationRepresented: 148_000,
    medianIncome: 52_000,
    renterFraction: 0.55,
    currentSentiment: 68,
    policyPreferences: {
      housing: 0.65, transit: 0.72, taxes: 0.45,
      safety: 0.68, business: 0.70, environment: 0.62,
    },
    currentQuote: '"Happy with the progress, but watch the property taxes."',
    avatarColor: '#F59E0B',
  },
  {
    id: 'group-higher',
    label: 'Higher Income',
    incomeGroup: 'higher',
    populationRepresented: 65_000,
    medianIncome: 112_000,
    renterFraction: 0.40,
    currentSentiment: 81,
    policyPreferences: {
      housing: 0.30, transit: 0.40, taxes: 0.20,
      safety: 0.72, business: 0.80, environment: 0.68,
    },
    currentQuote: '"City is becoming world class. Keep up the business investment."',
    avatarColor: '#10B981',
  },
];

// ------ POLICIES (15 Pittsburgh-specific) -------------------

export const initialPolicies: Policy[] = [
  // === HOUSING ===
  {
    id: 'pol-landbank',
    name: 'Fund City Land Bank',
    description: 'Convert vacant lots to affordable housing in Homewood, Hazelwood, and Larimer. Addresses 28% vacancy rate in disinvested neighborhoods.',
    category: 'housing',
    upfrontCost: 800_000,
    recurringCost: 120_000,
    status: 'proposed',
    affectedNeighborhoods: ['homewood', 'hazelwood'],
    pittsburghNote: 'Pittsburgh Land Bank holds 3,000+ parcels. Legislation passed 2014 but funding remains inadequate.',
    effects: [
      { label: 'Housing supply +180 units', delta: 180, field: 'housingSupply', isPositive: true, turnsDelay: 3, affectedNeighborhoods: ['homewood', 'hazelwood'] },
      { label: 'Lower-income happiness +8', delta: 8, field: 'happiness', isPositive: true, turnsDelay: 3, affectedNeighborhoods: ['homewood'] },
      { label: 'Budget −$800,000', delta: -800_000, field: 'treasury', isPositive: false, turnsDelay: 0, affectedNeighborhoods: [] },
    ],
  },
  {
    id: 'pol-inclusionary-zoning',
    name: 'Inclusionary Zoning — Lawrenceville',
    description: 'Require 15% affordable units in all new Lawrenceville developments over 10 units. Slows displacement of longtime renters.',
    category: 'housing',
    upfrontCost: 0,
    recurringCost: 0,
    status: 'proposed',
    affectedNeighborhoods: ['lawrenceville'],
    pittsburghNote: 'Pittsburgh lacks mandatory inclusionary zoning; this is a long-standing advocacy demand.',
    effects: [
      { label: 'Gentrification pressure −0.15 in Lawrenceville', delta: -0.15, field: 'gentrificationPressure', isPositive: true, turnsDelay: 2, affectedNeighborhoods: ['lawrenceville'] },
      { label: 'Middle-income happiness +5', delta: 5, field: 'happiness', isPositive: true, turnsDelay: 2, affectedNeighborhoods: ['lawrenceville'] },
      { label: 'Developer approval −4%', delta: -4, field: 'approval', isPositive: false, turnsDelay: 1, affectedNeighborhoods: [] },
    ],
  },
  {
    id: 'pol-hillside-stabilization',
    name: 'Hillside Stabilization Program',
    description: 'Landslide remediation on steep slopes in Mt. Washington, Beechview, and Brookline. Pittsburgh averages 3+ slope failures per year.',
    category: 'housing',
    upfrontCost: 1_200_000,
    recurringCost: 80_000,
    status: 'proposed',
    affectedNeighborhoods: ['mount_washington'],
    pittsburghNote: '23 Pittsburgh neighborhoods sit on slopes rated unstable by USGS. A 2018 slide closed Forbes Ave for weeks.',
    effects: [
      { label: 'Hillside risk −0.18', delta: -0.18, field: 'hillsideRisk', isPositive: true, turnsDelay: 2, affectedNeighborhoods: ['mount_washington'] },
      { label: 'Property values +4%', delta: 0.04, field: 'propertyValue', isPositive: true, turnsDelay: 3, affectedNeighborhoods: ['mount_washington'] },
      { label: 'Budget −$1,200,000', delta: -1_200_000, field: 'treasury', isPositive: false, turnsDelay: 0, affectedNeighborhoods: [] },
    ],
  },
  // === TRANSIT ===
  {
    id: 'pol-busway-extension',
    name: 'East Busway Frequency Increase',
    description: 'Add peak-hour bus service to Homewood, Hazelwood, and hilltop neighborhoods underserved by current Port Authority schedules.',
    category: 'transit',
    upfrontCost: 400_000,
    recurringCost: 200_000,
    status: 'proposed',
    affectedNeighborhoods: ['homewood', 'hazelwood', 'mount_washington'],
    pittsburghNote: 'Port Authority\'s East Busway is the busiest busway in the U.S. — hilltop service remains inadequate.',
    effects: [
      { label: 'Transit access +12 in hilltops', delta: 12, field: 'transitAccess', isPositive: true, turnsDelay: 1, affectedNeighborhoods: ['homewood', 'hazelwood', 'mount_washington'] },
      { label: 'Lower-income happiness +6', delta: 6, field: 'happiness', isPositive: true, turnsDelay: 1, affectedNeighborhoods: ['homewood'] },
      { label: 'Recurring cost −$200,000/turn', delta: -200_000, field: 'expenses', isPositive: false, turnsDelay: 0, affectedNeighborhoods: [] },
    ],
  },
  {
    id: 'pol-incline-subsidy',
    name: 'Incline Resident Fare Subsidy',
    description: 'Subsidize Mount Washington incline fares for residents (not tourists). Supports transit-dependent hillside commuters.',
    category: 'transit',
    upfrontCost: 0,
    recurringCost: 60_000,
    status: 'proposed',
    affectedNeighborhoods: ['mount_washington'],
    pittsburghNote: 'Duquesne Incline fares are $2.50 one-way. Locals use it daily; tourists drive up operating costs.',
    effects: [
      { label: 'Mt. Washington happiness +7', delta: 7, field: 'happiness', isPositive: true, turnsDelay: 0, affectedNeighborhoods: ['mount_washington'] },
      { label: 'Transit score +4', delta: 4, field: 'transitScore', isPositive: true, turnsDelay: 0, affectedNeighborhoods: [] },
      { label: 'Recurring cost −$60,000/turn', delta: -60_000, field: 'expenses', isPositive: false, turnsDelay: 0, affectedNeighborhoods: [] },
    ],
  },
  {
    id: 'pol-light-rail-east',
    name: 'Light Rail East End Extension',
    description: 'Extend the T light rail across the Allegheny into the East End, connecting Oakland, Shadyside, and East Liberty to downtown.',
    category: 'transit',
    upfrontCost: 4_500_000,
    recurringCost: 350_000,
    status: 'proposed',
    affectedNeighborhoods: ['oakland', 'shadyside', 'lawrenceville'],
    pittsburghNote: 'The T only crosses the Mon; crossing the Allegheny to the East End is a 30-year advocacy goal.',
    effects: [
      { label: 'Transit score +18 citywide', delta: 18, field: 'transitScore', isPositive: true, turnsDelay: 5, affectedNeighborhoods: [] },
      { label: 'Property values +8% along corridor', delta: 0.08, field: 'propertyValue', isPositive: true, turnsDelay: 4, affectedNeighborhoods: ['oakland', 'shadyside'] },
      { label: 'Rent +12% (displacement risk)', delta: 0.12, field: 'averageRent', isPositive: false, turnsDelay: 5, affectedNeighborhoods: ['lawrenceville'] },
      { label: 'Budget −$4,500,000', delta: -4_500_000, field: 'treasury', isPositive: false, turnsDelay: 0, affectedNeighborhoods: [] },
    ],
  },
  // === TAXES ===
  {
    id: 'pol-pilot-payments',
    name: 'Negotiate PILOT Payments from Universities & Hospitals',
    description: 'Challenge nonprofit property tax exemptions. Secure Payments in Lieu of Taxes from Pitt, CMU, and UPMC — the city\'s largest landowners — to fund city services.',
    category: 'taxes',
    upfrontCost: 200_000,      // legal costs
    recurringCost: -1_800_000, // net revenue (negative = income)
    status: 'proposed',
    affectedNeighborhoods: ['oakland'],
    pittsburghNote: '42% of Pittsburgh\'s assessed property value is tax-exempt. Boston secured $32M in PILOT payments from Harvard. Legal challenge likely.',
    effects: [
      { label: 'Revenue +$1,800,000/turn', delta: 1_800_000, field: 'revenue', isPositive: true, turnsDelay: 2, affectedNeighborhoods: [] },
      { label: 'Institutional approval −18%', delta: -18, field: 'approval', isPositive: false, turnsDelay: 1, affectedNeighborhoods: ['oakland'] },
      { label: 'Legal challenge risk (event)', delta: 0, field: 'approval', isPositive: false, turnsDelay: 3, affectedNeighborhoods: [] },
    ],
  },
  {
    id: 'pol-land-value-tax',
    name: 'Land Value Tax Shift',
    description: 'Tax land more heavily than structures — incentivizes development of vacant lots, reduces speculative holding. Pittsburgh used this policy 1913–2001.',
    category: 'taxes',
    upfrontCost: 100_000,     // admin / assessment costs
    recurringCost: -300_000,  // net positive via development
    status: 'proposed',
    affectedNeighborhoods: ['homewood', 'hazelwood', 'hill_district'],
    pittsburghNote: 'Pittsburgh had a two-rate land value tax longer than any U.S. city. Abandoned in 2001 amid reassessment controversy.',
    effects: [
      { label: 'Revenue +$300,000/turn', delta: 300_000, field: 'revenue', isPositive: true, turnsDelay: 2, affectedNeighborhoods: [] },
      { label: 'Vacancy rate −8% in disinvested areas', delta: -0.08, field: 'vacancyRate', isPositive: true, turnsDelay: 3, affectedNeighborhoods: ['homewood', 'hazelwood'] },
      { label: 'Homeowner approval −6%', delta: -6, field: 'approval', isPositive: false, turnsDelay: 1, affectedNeighborhoods: [] },
    ],
  },
  {
    id: 'pol-commuter-tax',
    name: 'Increase Local Services / Commuter Tax',
    description: 'Raise the tax on suburban workers who use Pittsburgh infrastructure but pay no city income tax. Earned income for non-residents.',
    category: 'taxes',
    upfrontCost: 50_000,
    recurringCost: -600_000,
    status: 'proposed',
    affectedNeighborhoods: [],
    pittsburghNote: 'Pittsburgh has 300,000 daily in-commuters who pay no city earned income tax. Regional resistance is fierce.',
    effects: [
      { label: 'Revenue +$600,000/year', delta: 600_000, field: 'revenue', isPositive: true, turnsDelay: 1, affectedNeighborhoods: [] },
      { label: 'More funds for services', delta: 0, field: 'expenses', isPositive: true, turnsDelay: 1, affectedNeighborhoods: [] },
      { label: 'Higher-income happiness −5', delta: -5, field: 'happiness', isPositive: false, turnsDelay: 1, affectedNeighborhoods: ['shadyside'] },
    ],
  },
  // === SAFETY ===
  {
    id: 'pol-bridge-inspection',
    name: 'Emergency Bridge Inspection & Repair',
    description: 'Accelerated structural inspection of 446 city bridges and immediate repair of those rated in poor condition.',
    category: 'safety',
    upfrontCost: 2_200_000,
    recurringCost: 150_000,
    status: 'proposed',
    affectedNeighborhoods: [],
    pittsburghNote: 'Pittsburgh has more bridges per capita than any U.S. city. A 2022 Forbes Ave bridge collapsed hours before Biden visited.',
    effects: [
      { label: 'Bridge condition avg +15', delta: 15, field: 'bridgeConditionAvg', isPositive: true, turnsDelay: 2, affectedNeighborhoods: [] },
      { label: 'Safety score +8', delta: 8, field: 'safetyScore', isPositive: true, turnsDelay: 2, affectedNeighborhoods: [] },
      { label: 'Bridge failure event risk −60%', delta: -0.6, field: 'safetyScore', isPositive: true, turnsDelay: 1, affectedNeighborhoods: [] },
      { label: 'Budget −$2,200,000', delta: -2_200_000, field: 'treasury', isPositive: false, turnsDelay: 0, affectedNeighborhoods: [] },
    ],
  },
  {
    id: 'pol-sewer-overflow',
    name: 'Combined Sewer Overflow Remediation',
    description: 'Separate storm and sanitary sewers to stop raw sewage discharge into the Allegheny and Monongahela after heavy rain.',
    category: 'safety',
    upfrontCost: 3_400_000,
    recurringCost: 0,
    status: 'proposed',
    affectedNeighborhoods: [],
    pittsburghNote: 'Pittsburgh\'s ALCOSAN faces a $2.3B consent decree. Overflow events close rivers to recreation for days at a time.',
    effects: [
      { label: 'Environment score +12', delta: 12, field: 'environmentScore', isPositive: true, turnsDelay: 3, affectedNeighborhoods: [] },
      { label: 'River flood damage −25%', delta: -0.25, field: 'riverFloodRisk', isPositive: true, turnsDelay: 3, affectedNeighborhoods: [] },
      { label: 'Budget −$3,400,000', delta: -3_400_000, field: 'treasury', isPositive: false, turnsDelay: 0, affectedNeighborhoods: [] },
    ],
  },
  // === BUSINESS ===
  {
    id: 'pol-robotics-corridor',
    name: 'Robotics & AI Corridor Incentives',
    description: 'Tax abatements and city grants to retain CMU spinoffs in Pittsburgh. Counter the talent drain to Bay Area and NYC.',
    category: 'business',
    upfrontCost: 1_000_000,
    recurringCost: 200_000,
    status: 'proposed',
    affectedNeighborhoods: ['oakland', 'strip_district'],
    pittsburghNote: 'CMU graduates 2,000+ CS/ML students/year. Waymo, Aurora, and Uber ATG all have Pittsburgh roots. Many leave.',
    effects: [
      { label: 'Jobs +800 high-wage in Oakland/Strip', delta: 800, field: 'jobs', isPositive: true, turnsDelay: 3, affectedNeighborhoods: ['oakland', 'strip_district'] },
      { label: 'Population +400 (in-migration)', delta: 400, field: 'population', isPositive: true, turnsDelay: 4, affectedNeighborhoods: [] },
      { label: 'Revenue +$450,000/turn (new tax base)', delta: 450_000, field: 'revenue', isPositive: true, turnsDelay: 4, affectedNeighborhoods: [] },
      { label: 'Budget −$1,000,000', delta: -1_000_000, field: 'treasury', isPositive: false, turnsDelay: 0, affectedNeighborhoods: [] },
    ],
  },
  {
    id: 'pol-butler-street-grants',
    name: 'Butler Street Small Business Grants',
    description: 'Emergency grants to legacy Butler Street businesses facing rent increases due to rapid Lawrenceville gentrification.',
    category: 'business',
    upfrontCost: 300_000,
    recurringCost: 80_000,
    status: 'proposed',
    affectedNeighborhoods: ['lawrenceville'],
    pittsburghNote: 'Butler Street has lost 40% of its legacy businesses to rent increases since 2015. Cultural displacement follows economic.',
    effects: [
      { label: 'Lawrenceville business retention +12', delta: 12, field: 'jobs', isPositive: true, turnsDelay: 1, affectedNeighborhoods: ['lawrenceville'] },
      { label: 'Middle-income happiness +6', delta: 6, field: 'happiness', isPositive: true, turnsDelay: 1, affectedNeighborhoods: ['lawrenceville'] },
      { label: 'Budget −$300,000', delta: -300_000, field: 'treasury', isPositive: false, turnsDelay: 0, affectedNeighborhoods: [] },
    ],
  },
  // === ENVIRONMENT ===
  {
    id: 'pol-air-quality',
    name: 'Mon Valley Air Quality Enforcement',
    description: 'Stricter enforcement of air quality standards against industrial emitters in the Monongahela Valley. Improves health outcomes, risks industrial jobs.',
    category: 'environment',
    upfrontCost: 500_000,
    recurringCost: 100_000,
    status: 'proposed',
    affectedNeighborhoods: ['hazelwood'],
    pittsburghNote: 'Clairton Coke Works is the largest source of SO₂ emissions east of the Mississippi. Hazelwood and the Hill District bear the burden.',
    effects: [
      { label: 'Air quality index −30 (improvement)', delta: -30, field: 'airQualityIndex', isPositive: true, turnsDelay: 2, affectedNeighborhoods: [] },
      { label: 'Lower-income happiness +5 (health)', delta: 5, field: 'happiness', isPositive: true, turnsDelay: 2, affectedNeighborhoods: ['hazelwood', 'homewood'] },
      { label: 'Industrial jobs −150', delta: -150, field: 'jobs', isPositive: false, turnsDelay: 2, affectedNeighborhoods: ['hazelwood'] },
    ],
  },
  {
    id: 'pol-riverfront-trails',
    name: 'Riverfront Trail & Green Infrastructure',
    description: 'Extend the Three Rivers Heritage Trail, add bioswales and green stormwater infrastructure along riverbanks.',
    category: 'environment',
    upfrontCost: 1_500_000,
    recurringCost: 50_000,
    status: 'proposed',
    affectedNeighborhoods: ['strip_district', 'south_side_flats', 'lawrenceville'],
    pittsburghNote: 'The Three Rivers Heritage Trail already runs 33 miles. Gaps in the south shore and East End remain.',
    effects: [
      { label: 'Environment score +10', delta: 10, field: 'environmentScore', isPositive: true, turnsDelay: 2, affectedNeighborhoods: [] },
      { label: 'Citywide happiness +4', delta: 4, field: 'happiness', isPositive: true, turnsDelay: 3, affectedNeighborhoods: [] },
      { label: 'River flood risk −8%', delta: -0.08, field: 'riverFloodRisk', isPositive: true, turnsDelay: 2, affectedNeighborhoods: [] },
      { label: 'Budget −$1,500,000', delta: -1_500_000, field: 'treasury', isPositive: false, turnsDelay: 0, affectedNeighborhoods: [] },
    ],
  },
];

// ------ BRIDGES ---------------------------------------------

export const initialBridges: Bridge[] = [
  {
    id: 'br-clemente',
    name: 'Roberto Clemente Bridge',
    condition: 78, repairCost: 420_000,
    type: 'suspension', isThreeSisters: true,
    mapX: 0.40, mapY: 0.30,
    affectedNeighborhoods: ['golden_triangle', 'strip_district'],
    lastInspectionTurn: 0,
  },
  {
    id: 'br-warhol',
    name: 'Andy Warhol Bridge',
    condition: 71, repairCost: 580_000,
    type: 'suspension', isThreeSisters: true,
    mapX: 0.44, mapY: 0.27,
    affectedNeighborhoods: ['golden_triangle', 'strip_district'],
    lastInspectionTurn: 0,
  },
  {
    id: 'br-rachel-carson',
    name: 'Rachel Carson Bridge',
    condition: 65, repairCost: 710_000,
    type: 'suspension', isThreeSisters: true,
    mapX: 0.48, mapY: 0.24,
    affectedNeighborhoods: ['golden_triangle', 'lawrenceville'],
    lastInspectionTurn: 0,
  },
  {
    id: 'br-smithfield',
    name: 'Smithfield Street Bridge',
    condition: 55, repairCost: 1_200_000,
    type: 'truss', isThreeSisters: false,
    mapX: 0.38, mapY: 0.50,
    affectedNeighborhoods: ['golden_triangle', 'south_side_flats'],
    lastInspectionTurn: 0,
  },
  {
    id: 'br-fort-pitt',
    name: 'Fort Pitt Bridge',
    condition: 62, repairCost: 2_400_000,
    type: 'arch', isThreeSisters: false,
    mapX: 0.32, mapY: 0.52,
    affectedNeighborhoods: ['golden_triangle', 'mount_washington'],
    lastInspectionTurn: 0,
  },
  {
    id: 'br-liberty',
    name: 'Liberty Bridge',
    condition: 48, repairCost: 3_100_000,
    type: 'truss', isThreeSisters: false,
    mapX: 0.35, mapY: 0.55,
    affectedNeighborhoods: ['golden_triangle', 'south_side_flats', 'mount_washington'],
    lastInspectionTurn: 0,
  },
];

// ------ INITIAL EVENTS (empty — generated by engine) --------

export const initialEvents: GameEvent[] = [];

// ------ INITIAL SNAPSHOTS (turn 0 baseline) -----------------

export const initialSnapshots: SimulationSnapshot[] = [
  {
    turn: 0,
    treasury: 2_480_000,
    revenue: 2_910_000,
    expenses: 2_430_000,
    happiness: 72,
    approval: 68,
    population: 302_000,
    averageRent: 1_340,
    neighborhoodHappiness: {
      shadyside: 81, lawrenceville: 68, homewood: 42,
      oakland: 62, golden_triangle: 70, mount_washington: 65,
      hill_district: 38, strip_district: 72, south_side_flats: 62, hazelwood: 44,
    },
    neighborhoodRent: {
      shadyside: 1980, lawrenceville: 1540, homewood: 740,
      oakland: 1620, golden_triangle: 2100, mount_washington: 1180,
      hill_district: 680, strip_district: 1780, south_side_flats: 1250, hazelwood: 750,
    },
    activeEventIds: [],
  },
];
