/** Each spoken segment directs one stop of the introductory tour. */
export const MAYOR_INTRODUCTION = [
  { tour: 'overview', text: 'Welcome to State of us. State of you. State of the community. State of the people. Every person in this city has a life, a need, and a stake in what we do next.' },
  { tour: 'overview', text: 'I’m the mayor, and you’re our city’s budget planner. You’ll decide which policies we can afford: homes, transit, public services, and more. Your job is to balance the money we have with the happiness and well-being of the people who live here.' },
  { tour: 'overview', text: 'These choices matter. Money spent on one priority leaves less for another. A plan that helps one neighborhood may do little for the next, or make life harder for someone else. Listen to residents, watch who benefits, and keep the city’s finances healthy enough to help tomorrow, too. This is Pittsburgh. Let me show you the community you’ll be making those decisions for.' },
  { tour: 'downtown', text: 'This is Downtown, our city center at the meeting of the rivers. Decisions about jobs, transport and public services matter here, but their benefits won’t stop at the district boundary.' },
  { tour: 'pitt', text: 'Over here is Pitt and Oakland, with the university and hospitals. Students, workers and nearby households can experience the same policy very differently. A shorter commute might mean much more to one person than another.' },
  { tour: 'corporate', text: 'This is the Corporate District, our office and commercial hub. Supporting businesses can create opportunities, but we also need to ask who benefits and what the city is paying for.' },
  { tour: 'suburbs', text: 'And these are the Suburbs, our residential neighborhoods. Housing support could make a big difference to a family struggling with rent while doing very little for a homeowner elsewhere. People will compare those outcomes and talk about whether they feel fair.' },
  { tour: 'demo-house', text: 'Let’s try a small demonstration before you spend any money. Here’s a patch of trees. Imagine a plan to build low-income housing here. Watch as we clear the trees and put a new home on the lot.' },
  { tour: 'demo-result', text: 'There’s the new home. We’ve turned a wooded lot into housing. In a real plan, a family struggling with rent could benefit a lot, while neighbors might be upset about losing trees and green space. Construction also costs the city money. That’s the tradeoff: who gets help, who gives something up, and what we can afford. This is just a visual demonstration; your budget and resident statistics haven’t changed.' },
  { tour: 'controls', text: 'You can explore for yourself: drag the map to move around, scroll or use the plus and minus buttons to zoom, and click or drag the minimap to jump across the city. Reset returns the map to its overview. Click a district label to take a closer look.' },
  { tour: 'overview', text: 'Most days, we’ll have five policies for you to choose from, curated and influenced by local news, city initiatives, and surveys. These are simulation plans, so the costs and outcomes are ours to explore. Some days an emergency will need a different kind of decision. You’ll have six days to try running the city, then we’ll look at who your choices helped and who still needs support. After that, you can keep going in sandbox play.' },
  { tour: 'choices', text: 'Here are your five plans. Open a card to see what it does, its cost and tradeoffs. Confirming a plan applies your choice and moves us into the next day. Watch the budget and the residents’ reactions, not just the citywide average. My assistant will help each day. I’ll return on Days 3, 6, 9, and every third day after that to review the results.' },
] as const;
